### ISSUE TITLE
Improvements requested

### ISSUE THREAD

**Issue by klutarevich** [pagandomen/practicentasks#1]
It's a good start but the final part needs to be improved in 2 ways:
- If AGS has only 1 instance your "remove instance" call will terminate the only running instance which is not acceptable for 24x7 system. Please, come up with a different way of replacing instances (hint: you should be able to do this w/o explicitly terminating instances) 
- 300 seconds might not be enough for the instance to bootstrap itself. You need to make sure the instance is healthy before moving on.

**Comment by pagandomen** [comment]
Steps were added into script:
- Desirable state is increased by 1 in the beginning, to be sure at least one new instance is up and running. After successful upgrade parameter is set to original amount
- Old instances are detached from ASG and then terminated as last step 
- Check for Health and LifecycleState was added

**Comment by klutarevich** [comment]
You can do even better, make it simpler. Try to avoid terminating instances explicitly (don't use Remove-EC2 instances). 
Hint: read about different termination policies on ASG

**Comment by pagandomen** [comment]
Avoid manual terminating via manipulating with Desired state. ASG automatically clean up old instances when DS is decreased

**Comment by klutarevich** [comment]
Looks good
